### ISSUE TITLE
Usage example not working 'as is'

### ISSUE THREAD

**Issue by odubuc** [FWeinb/electron-screenshot-service#13]
I'm launching the usage example and I'm having the following error.

A Javascript error occurred in the main process
Uncaught Exception:
Error: connect EADDRNOTAVAIL 0.0.0.0:52799
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)

**Comment by FWeinb** [comment]
What operating system are you using?

**Comment by FWeinb** [comment]
Closing due to inactivity. Please reopen if you can provide more details.
