### ISSUE TITLE
electron error while installing

### ISSUE THREAD

**Issue by mtib** [FWeinb/electron-screenshot-service#30]
I am quite new to the npm packaging, so this might be something obvious, but when running

``` bash
npm install electron-screenshot-service #or
sudo npm install -g electron-screenshot-service
```

or even running `root@pc:/root/npm# npm install electron-screenshot-service` errored, so it can't be permission, can it?

terminal:

```
> electron@1.3.4 postinstall /root/npm/node_modules/electron
> node install.js

module.js:457
    throw err;
    ^

Error: Cannot find module '/root/npm/node_modules/electron/install.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
/root/npm
├─┬ axon@2.0.2 
│ ├── amp@0.3.1 
│ ├── amp-message@0.1.2 
│ ├── configurable@0.0.1 
│ ├─┬ debug@2.2.0 
│ │ └── ms@0.7.1 
│ └── escape-regexp@0.0.1 
├── bluebird@3.4.6 
└─┬ cross-spawn@4.0.0 
  ├─┬ lru-cache@4.0.1 
  │ ├── pseudomap@1.0.2 
  │ └── yallist@2.0.0 
  └─┬ which@1.2.11 
    └── isexe@1.1.2 

npm WARN enoent ENOENT: no such file or directory, open '/root/npm/package.json'
npm WARN npm No description
npm WARN npm No repository field.
npm WARN npm No README data
npm WARN npm No license field.
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "electron-screenshot-service"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! electron@1.3.4 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.3.4 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm/npm-debug.log
```

log [npm-debug.log](https://gist.githubusercontent.com/mtib/966a63bb85392a60ed29bd8869c8828a/raw/4d6386e2e4af00083935f735cdfb6eafb49f1022/npm-debug.log)

It says the error has something to do with electron, but I can run/develop fine for electron.

Thanks for your time!

**Comment by FWeinb** [comment]
I just tested it locally and can't reproduce this error.
